### ISSUE TITLE
images in TextMate::UI.complete

### ISSUE THREAD

**Issue by fab1an** [textmate/bundle-support.tmbundle#17]
Hi, I can't get images to work with a ruby-command. This is my code:

```ruby

#!/usr/bin/env ruby18 -wKU
require ENV['TM_SUPPORT_PATH'] + '/lib/ui.rb'

choices = [
  {"display"=> "test1", "image"=>"func"},
]
TextMate::UI.complete(choices, :images => {
  "func" => "/Applications/test.png"
});
```

**Comment by sorbits** [comment]
You need to register the images first, there was a thread about this on the mailing list, see e.g. http://lists.macromates.com/textmate/2016-July/039687.html
