### ISSUE TITLE
TextMate::UI.complete does not work

### ISSUE THREAD

**Issue by Spalf** [textmate/bundle-support.tmbundle#18]
Hi!

I [opened](https://github.com/syscrusher/golang.tmbundle/issues/27) the ticket for the golang.tmbundle.
But looks is the bundle-support issue.

**Comment by Spalf** [comment]
Walk around:
Change ruby version in [golang.tmbundle/Commands/Complete.tmCommand](https://github.com/syscrusher/golang.tmbundle/blob/master/Commands/Complete.tmCommand) to "ruby18 -wKU"

**Comment by infininight** [comment]
As the issue found, the support libraries currently require the use of `ruby18`.
