### ISSUE TITLE
TextMate::Executor.run show broken preview

### ISSUE THREAD

**Issue by milligramme** [textmate/bundle-support.tmbundle#26]
when update beta12.4 -> 12.8

TextMate::Executor.run show different and broken preview in each `run`.

```go
package main

import "fmt"

func main() {
  fmt.Println("Hello")
}
```

run this snippet three times, it returned like below.

![screen shot 2016-09-05 9 57 37](https://cloud.githubusercontent.com/assets/294127/18235011/809ef932-734f-11e6-8dae-7955480fde6c.png)
![screen shot 2016-09-05 9 57 43](https://cloud.githubusercontent.com/assets/294127/18235016/861dd6b2-734f-11e6-87e7-9000c20b5767.png)
![screen shot 2016-09-05 9 57 47](https://cloud.githubusercontent.com/assets/294127/18235025/93347c3e-734f-11e6-9574-e8a68672e3da.png)

so I remove all Avian/Bundles and try this again, but nothing was solved.

**Comment by sorbits** [comment]
When you see the broken output please select View → View Source and 
provide the raw HTML for the broken output.

For the records here are the steps to do a complete factory reset, but I 
don’t think your issue should be caused by local changes (since you 
report it as not 100% reproducible): 
https://github.com/textmate/textmate/wiki/Reverting-To-Defaults

**Comment by milligramme** [comment]
I also tried "Reverting-To-Defaults", but nothing turn out good.

I posted 6 view sources to 

https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424



- https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424#file-1-html-L171
- https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424#file-2-html-L169
- https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424#file-3-html-L170-L172
- https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424#file-4-html-L173
- https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424#file-5-html-L171-L173
- https://gist.github.com/milligramme/b4ea6001992fcbbec62d6071d03d3424#file-6-html-L10

**Comment by sorbits** [comment]
Please go to Preferences → Software Update and hold down option (⌥) 
while clicking Check Now.

This should update to v2.0-beta.12.9, let me know if you see the issue 
with this build.

**Comment by milligramme** [comment]
It seems to be fixed in beta.12.9
Thank you so much.
