### ISSUE TITLE
Include 64-Bit Version of CocoaDialog in Bundle

### ISSUE THREAD

**Issue by sanssecours** [textmate/bundle-support.tmbundle#31]
# Steps to Reproduce the Issue

1. Install [Skim](https://skim-app.sourceforge.io) and the [LaTeX bundle](https://www.github.com/textmate/latex.tmbundle) (in “Preferences…” → “Bundles”)

2. Create a new document with the following content:

   ```tex
   \documentclass{article}

   \begin{document}
     Test
   \end{document}
   ```

3. Save the file using the name `Test.tex`
4. Invoke the command “Watch Document” (<kbd>^</kbd> + <kbd>⌘</kbd> + <kbd>W</kbd>)

# Expected Result

TextMate compiles the document, and opens the resulting PDF in Skim.

# Actual Result

TextMate shows the following window:

<img width="532" alt="cocoadialog" src="https://user-images.githubusercontent.com/691989/51320096-1818bb00-1a5f-11e9-8231-eb90053def12.png">

informing us, that the included version of CocoaDialog should be updated. After we click on the “OK” button everything works fine.

# Additional Information

I built the current version of [CocoaDialog](https://github.com/cocoadialog/cocoadialog) and replaced (`CocoaDialog.app`) with the newly-built application. Afterwards I changed the name of `cocoadialog.app` and `cocadialog` to CamelCase (`CocoaDialog`). Unfortunately that did not work. It seems like `CocoaDialog` is crashing with exit value `51`.

# System Information

- TextMate `2.0-rc.22`
- macOS `10.14.2`

**Comment by sorbits** [comment]
I was unable to build CocoaDialog myself, and there are no official binaries, but [this comment has a link to a build](https://github.com/cocoadialog/cocoadialog/issues/108#issuecomment-396059785).

I have yet to test it myself, but if it works, we can use one of these, but it’s not a good situation, we probably should fork CocoaDialog and revert it back to a simpler version that can be built and possibly also move bundle code away from using CocoaDialog.

**Comment by elia** [comment]
@sorbits @infininight Catilina is refusing to open CocoaDialog (says "Bad CPU Type"), I had a look around and found a possible replacement for CocoaDialog called Pashua (https://www.bluem.net/en/projects/pashua/). 

Even better to me would be to embed the functionality within textmate and have scripts ask it to show dialogs. That would enable great things like fuzzy search etc.
